name: default
run-name: default
on: [push]
env:
  DOCKER_BUILDKIT: 1
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: bin/docker-build.sh
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: jdbc-basicauth-proxy_amd64_alpine
          path: build/jdbc-basicauth-proxy_amd64_alpine
          retention-days: 7
      - name: Upload Docker image as artifact
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: ghcr.io/davidlukac/jdbc-basicauth-proxy/alpine:0.1.0-pipeline-test
          retention_days: "7"
#      - run: docker push ghcr.io/davidlukac/jdbc-basicauth-proxy/alpine:0.1.0-pipeline-test
