name: default
run-name: default
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - run: apk -U add --no-cache bash
      - run: bin/docker-build.sh
