name: Release
run-name: "release: ${{ github.triggering_actor }}@${{ github.ref_name }}"

on:
  push:
    tags:
#      - v*
      - test*
#on: [push]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -al
      - run: echo "${{ github.ref_type }}:${{ github.ref_name }}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            foo
